name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ejecutar pruebas
        run: npm test || echo "No hay pruebas configuradas"

      # 4. Escanear vulnerabilidades
      - name: Escaneo de vulnerabilidades
        run: npm audit --audit-level=moderate || true

      # 5. Desplegar al EC2
      - name: Desplegar al EC2
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USER }}
          key: ${{ secrets.TEST_SERVER_SSH_KEY }}
          script: |
            git pull
            cd /var/miapp/Guatecos/guatecoBE
            npm install -y
            sudo systemctl restart guateco
